version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    platform: linux/x86_64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "12345678aA@"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
