version: '3'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "12345678aA@"
    ports:
      - 127.0.0.1:1433:1433

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
    ports:
      - 127.0.0.1:5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8090:8080